import speech_recognition as sr
import pyttsx3
import os
import google.generativeai as genai

genai.configure(api_key="AIzaSyA8ZVgJCwN0o4e1Nb6UT5W8nBzX1ySrCEw")

# Create the model
generation_config = {
  "temperature": 0.25,
  "top_p": 0.9,
  "top_k": 40,
  "max_output_tokens": 25,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-1.5-flash",
  generation_config=generation_config,
)

while True:

    r = sr.Recognizer()

    def SpeakText(command):
        engine = pyttsx3.init()
        engine.say(command)
        engine.runAndWait()

    def live_audio_to_text():
        statement = str()

        try:
            with sr.Microphone() as source:
                r.adjust_for_ambient_noise(source, duration=0.5)
                audio_data = r.listen(source)
                statement = r.recognize_google(audio_data)
                statement = statement.lower()
                # SpeakText(statement)
                
        except sr.RequestError as e:
            statement = "Could not request results; {0}".format(e)
            
        except sr.UnknownValueError:
            statement = "Could not understand the audio"

        return statement
    
    statement = live_audio_to_text()
    print(statement)

    userinput = statement



    # # statement = input("Enter the statement: ")

    statement = statement.strip().lower()

    if (statement.startswith("voiceassist") or
        statement.startswith("voice assist") or
        statement.startswith("voice-assist") or
        statement.startswith("voice asisst") or
        statement.startswith("voiceasist") or
        statement.startswith("voiceassit") or
        statement.startswith("voice-a-sist") or
        statement.startswith("voices assist") or
        statement.startswith("voic assist") or
        statement.startswith("voiceist") or
        statement.startswith("voitassist") or
        statement.startswith("viss assist") or
        statement.startswith("voice asst") or
        statement.startswith("voice assistence") or
        statement.startswith("vayce assist") or
        statement.startswith("vyoice assist") or
        statement.startswith("voice - assist") or
        statement.startswith("voice_assist") or
        statement.startswith("voice-assit") or
        statement.startswith("voiceassistance") or
        statement.startswith("voice asistance") or
        statement.startswith("voit asisst") or
        statement.startswith("voiz assist") or
        statement.startswith("voice assist-") or
        statement.startswith("voices assistence") or
        statement.startswith("voise assist") or
        statement.startswith("voyce assist") or
        statement.startswith("voic assistt") or
        statement.startswith("voys assist") or
        statement.startswith("voiceasst") or
        statement.startswith("voice assists") or
        statement.startswith("voci assist") or
        statement.startswith("viceassist") or
        statement.startswith("voicassis") or
        statement.startswith("vocs assist") or
        statement.startswith("vcs assist") or
        statement.startswith("voice aseet") or
        statement.startswith("voce assist") or
        statement.startswith("vics assist") or
        statement.startswith("vice asisst") or
        statement.startswith("voix assist") or
        statement.startswith("voss assist") or
        statement.startswith("voice,assist") or
        statement.startswith("voice, assist") or 
        statement.startswith("vayce assist") or
        statement.startswith("voice assistant") or
        statement.startswith("voiceassistant") or
        statement.startswith("voice-assistant") or
        statement.startswith("voic assistant") or
        statement.startswith("vocs assistant") or
        statement.startswith("voice-assistantt") or
        statement.startswith("voicesassistant")):
        
        response = model.generate_content([
        "input: play music",
        "output: play music",
        "input: start music",
        "output: play music",
        "input: play the music",
        "output: play music",
        "input: put on music",
        "output: play music",
        "input: start the song",
        "output: play music",
        "input: play songs",
        "output: play music",
        "input: turn on music",
        "output: play music",
        "input: i want music",
        "output: play music",
        "input: music on",
        "output: play music",
        "input: play some music",
        "output: play music",
        "input: play my music",
        "output: play music",
        "input: put music",
        "output: play music",
        "input: play a music",
        "output: play music",
        "input: can you play music",
        "output: play music",
        "input: i need music",
        "output: play music",
        "input: let’s play music",
        "output: play music",
        "input: music please",
        "output: play music",
        "input: get the music going",
        "output: play music",
        "input: play the song",
        "output: play music",
        "input: i want to hear music",
        "output: play music",
        "input: pause music",
        "output: pause music",
        "input: stop the music",
        "output: pause music",
        "input: pause the song",
        "output: pause music",
        "input: stop playing music",
        "output: pause music",
        "input: pause the tune",
        "output: pause music",
        "input: halt the music",
        "output: pause music",
        "input: pause the song now",
        "output: pause music",
        "input: stop the music for a while",
        "output: pause music",
        "input: music off",
        "output: pause music",
        "input: pause the music please",
        "output: pause music",
        "input: hold music",
        "output: pause music",
        "input: stop the tunes",
        "output: pause music",
        "input: stop the sound",
        "output: pause music",
        "input: pause audio",
        "output: pause music",
        "input: music pause please",
        "output: pause music",
        "input: stop the music now",
        "output: pause music",
        "input: halt the song",
        "output: pause music",
        "input: can you pause music",
        "output: pause music",
        "input: pause that song",
        "output: pause music",
        "input: pause the track",
        "output: pause music",
        "input: next song",
        "output: next song",
        "input: play next song",
        "output: next song",
        "input: skip to next song",
        "output: next song",
        "input: next track",
        "output: next song",
        "input: skip the song",
        "output: next song",
        "input: next tune",
        "output: next song",
        "input: next music",
        "output: next song",
        "input: move to next song",
        "output: next song",
        "input: next track please",
        "output: next song",
        "input: skip to the next song",
        "output: next song",
        "input: play next track",
        "output: next song",
        "input: next song now",
        "output: next song",
        "input: change song",
        "output: next song",
        "input: go to next song",
        "output: next song",
        "input: next please",
        "output: next song",
        "input: move to next track",
        "output: next song",
        "input: skip the current song",
        "output: next song",
        "input: next song please",
        "output: next song",
        "input: change the song",
        "output: next song",
        "input: go ahead to next song",
        "output: next song",
        "input: previous song",
        "output: previous song",
        "input: play previous song",
        "output: previous song",
        "input: skip to previous song",
        "output: previous song",
        "input: previous track",
        "output: previous song",
        "input: go to previous song",
        "output: previous song",
        "input: previous music",
        "output: previous song",
        "input: move to previous song",
        "output: previous song",
        "input: previous tune",
        "output: previous song",
        "input: play the previous song",
        "output: previous song",
        "input: skip to the previous song",
        "output: previous song",
        "input: play last song",
        "output: previous song",
        "input: previous track please",
        "output: previous song",
        "input: go back to previous song",
        "output: previous song",
        "input: go to last song",
        "output: previous song",
        "input: previous song now",
        "output: previous song",
        "input: previous one",
        "output: previous song",
        "input: skip back to the previous song",
        "output: previous song",
        "input: go back to the track",
        "output: previous song",
        "input: play the last track",
        "output: previous song",
        "input: previous song please",
        "output: previous song",
        "input: volume up",
        "output: voulme up",
        "input: increase volume",
        "output: voulme up",
        "input: raise volume",
        "output: voulme up",
        "input: turn up the volume",
        "output: voulme up",
        "input: make volume louder",
        "output: voulme up",
        "input: volume higher",
        "output: voulme up",
        "input: turn the volume up",
        "output: voulme up",
        "input: increase the sound",
        "output: voulme up",
        "input: turn it up",
        "output: voulme up",
        "input: raise the volume please",
        "output: voulme up",
        "input: volume up please",
        "output: voulme up",
        "input: up the volume",
        "output: voulme up",
        "input: turn sound up",
        "output: voulme up",
        "input: make it louder",
        "output: voulme up",
        "input: increase the volume please",
        "output: voulme up",
        "input: boost the volume",
        "output: voulme up",
        "input: turn up sound",
        "output: voulme up",
        "input: turn the sound up",
        "output: voulme up",
        "input: volume louder",
        "output: voulme up",
        "input: raise sound",
        "output: voulme up",
        "input: volume down",
        "output: volume down",
        "input: decrease volume",
        "output: volume down",
        "input: lower volume",
        "output: volume down",
        "input: turn down the volume",
        "output: volume down",
        "input: make volume quieter",
        "output: volume down",
        "input: volume lower",
        "output: volume down",
        "input: turn the volume down",
        "output: volume down",
        "input: decrease the sound",
        "output: volume down",
        "input: turn it down",
        "output: volume down",
        "input: lower the volume please",
        "output: volume down",
        "input: volume down please",
        "output: volume down",
        "input: down the volume",
        "output: volume down",
        "input: turn sound down",
        "output: volume down",
        "input: make it quieter",
        "output: volume down",
        "input: decrease the volume please",
        "output: volume down",
        "input: reduce the volume",
        "output: volume down",
        "input: turn down sound",
        "output: volume down",
        "input: lower sound",
        "output: volume down",
        "input: volume softer",
        "output: volume down",
        "input: reduce sound",
        "output: volume down",
        "input: turn on AC",
        "output: turn on AC",
        "input: switch on the AC",
        "output: turn on AC",
        "input: start the AC",
        "output: turn on AC",
        "input: turn on the air conditioner",
        "output: turn on AC",
        "input: activate the AC",
        "output: turn on AC",
        "input: turn the AC on",
        "output: turn on AC",
        "input: switch on air conditioning",
        "output: turn on AC",
        "input: start the air conditioner",
        "output: turn on AC",
        "input: turn on the air cooling",
        "output: turn on AC",
        "input: switch on the air conditioning",
        "output: turn on AC",
        "input: power on the AC",
        "output: turn on AC",
        "input: switch the AC on",
        "output: turn on AC",
        "input: turn on the cooling system",
        "output: turn on AC",
        "input: activate air conditioning",
        "output: turn on AC",
        "input: start cooling the air",
        "output: turn on AC",
        "input: power on air conditioner",
        "output: turn on AC",
        "input: turn the air conditioning on",
        "output: turn on AC",
        "input: start the air cooling system",
        "output: turn on AC",
        "input: turn the AC system on",
        "output: turn on AC",
        "input: switch on the cooling system",
        "output: turn on AC",
        "input: turn off AC",
        "output: turn off AC",
        "input: switch off the AC",
        "output: turn off AC",
        "input: turn off the air conditioner",
        "output: turn off AC",
        "input: deactivate the AC",
        "output: turn off AC",
        "input: turn the AC off",
        "output: turn off AC",
        "input: switch off air conditioning",
        "output: turn off AC",
        "input: stop the AC",
        "output: turn off AC",
        "input: turn off the air cooling",
        "output: turn off AC",
        "input: power off the AC",
        "output: turn off AC",
        "input: switch the AC off",
        "output: turn off AC",
        "input: turn off air conditioner",
        "output: turn off AC",
        "input: shut down the AC",
        "output: turn off AC",
        "input: stop the air conditioning",
        "output: turn off AC",
        "input: turn the cooling system off",
        "output: turn off AC",
        "input: power off air conditioner",
        "output: turn off AC",
        "input: turn off the air conditioning system",
        "output: turn off AC",
        "input: turn off the cooling system",
        "output: turn off AC",
        "input: stop the air cooling",
        "output: turn off AC",
        "input: switch off the air conditioner",
        "output: turn off AC",
        "input: turn off the climate control",
        "output: turn off AC",
        "input: open driver window",
        "output: open driver window",
        "input: roll down driver window",
        "output: open driver window",
        "input: open the window",
        "output: open driver window",
        "input: lower driver window",
        "output: open driver window",
        "input: open the driver side window",
        "output: open driver window",
        "input: roll down the driver side window",
        "output: open driver window",
        "input: open window please",
        "output: open driver window",
        "input: lower the driver window",
        "output: open driver window",
        "input: driver window down",
        "output: open driver window",
        "input: open the window on the driver's side",
        "output: open driver window",
        "input: open the window now",
        "output: open driver window",
        "input: open my driver window",
        "output: open driver window",
        "input: lower the window on the driver's side",
        "output: open driver window",
        "input: driver window open",
        "output: open driver window",
        "input: roll down the window on the driver's side",
        "output: open driver window",
        "input: open the side window",
        "output: open driver window",
        "input: roll down the side window",
        "output: open driver window",
        "input: open the car window",
        "output: open driver window",
        "input: open window on driver side",
        "output: open driver window",
        "input: open the front window",
        "output: open driver window",
        "input: close driver window",
        "output: close driver window",
        "input: roll up driver window",
        "output: close driver window",
        "input: close the window",
        "output: close driver window",
        "input: raise driver window",
        "output: close driver window",
        "input: close the driver side window",
        "output: close driver window",
        "input: roll up the driver side window",
        "output: close driver window",
        "input: close window please",
        "output: close driver window",
        "input: raise the driver window",
        "output: close driver window",
        "input: driver window up",
        "output: close driver window",
        "input: close the window on the driver's side",
        "output: close driver window",
        "input: close the window now",
        "output: close driver window",
        "input: close my driver window",
        "output: close driver window",
        "input: raise the window on the driver's side",
        "output: close driver window",
        "input: driver window closed",
        "output: close driver window",
        "input: roll up the window on the driver's side",
        "output: close driver window",
        "input: close the side window",
        "output: close driver window",
        "input: roll up the side window",
        "output: close driver window",
        "input: close the car window",
        "output: close driver window",
        "input: close window on driver side",
        "output: close driver window",
        "input: close the front window",
        "output: close driver window",
        "input: show traffic updates",
        "output: show traffic updates",
        "input: check traffic",
        "output: show traffic updates",
        "input: traffic updates",
        "output: show traffic updates",
        "input: show me the traffic updates",
        "output: show traffic updates",
        "input: check for traffic",
        "output: show traffic updates",
        "input: show current traffic",
        "output: show traffic updates",
        "input: traffic information",
        "output: show traffic updates",
        "input: traffic status",
        "output: show traffic updates",
        "input: give me traffic updates",
        "output: show traffic updates",
        "input: check traffic conditions",
        "output: show traffic updates",
        "input: display traffic updates",
        "output: show traffic updates",
        "input: show live traffic",
        "output: show traffic updates",
        "input: show traffic conditions",
        "output: show traffic updates",
        "input: update me on traffic",
        "output: show traffic updates",
        "input: check for traffic information",
        "output: show traffic updates",
        "input: traffic alerts",
        "output: show traffic updates",
        "input: display traffic information",
        "output: show traffic updates",
        "input: show road conditions",
        "output: show traffic updates",
        "input: check traffic status",
        "output: show traffic updates",
        "input: show real-time traffic updates",
        "output: show traffic updates",
        "input: lock doors",
        "output: lock doors",
        "input: lock the doors",
        "output: lock doors",
        "input: lock the car doors",
        "output: lock doors",
        "input: close the doors and lock",
        "output: lock doors",
        "input: lock all doors",
        "output: lock doors",
        "input: secure the doors",
        "output: lock doors",
        "input: lock the vehicle doors",
        "output: lock doors",
        "input: lock car doors now",
        "output: lock doors",
        "input: please lock the doors",
        "output: lock doors",
        "input: lock all car doors",
        "output: lock doors",
        "input: lock the front doors",
        "output: lock doors",
        "input: lock my doors",
        "output: lock doors",
        "input: lock doors please",
        "output: lock doors",
        "input: secure the car doors",
        "output: lock doors",
        "input: close and lock the doors",
        "output: lock doors",
        "input: lock all of the doors",
        "output: lock doors",
        "input: lock the doors now",
        "output: lock doors",
        "input: lock the car right now",
        "output: lock doors",
        "input: lock the doors on the car",
        "output: lock doors",
        "input: secure the doors now",
        "output: lock doors",
        "input: unlock doors",
        "output: unlock doors",
        "input: unlock the doors",
        "output: unlock doors",
        "input: unlock the car doors",
        "output: unlock doors",
        "input: open the doors",
        "output: unlock doors",
        "input: unlock all doors",
        "output: unlock doors",
        "input: unlock the vehicle doors",
        "output: unlock doors",
        "input: unlock car doors now",
        "output: unlock doors",
        "input: please unlock the doors",
        "output: unlock doors",
        "input: unlock all car doors",
        "output: unlock doors",
        "input: unlock the front doors",
        "output: unlock doors",
        "input: unlock my doors",
        "output: unlock doors",
        "input: unlock the doors please",
        "output: unlock doors",
        "input: open and unlock the doors",
        "output: unlock doors",
        "input: unlock the car now",
        "output: unlock doors",
        "input: unlock the doors on the car",
        "output: unlock doors",
        "input: unlock the doors now",
        "output: unlock doors",
        "input: unlock the car doors immediately",
        "output: unlock doors",
        "input: unlock all of the doors",
        "output: unlock doors",
        "input: unlock the back doors",
        "output: unlock doors",
        "input: unlock the doors and open",
        "output: unlock doors",
        "input: activate emergency mode",
        "output: activate emergency mode",
        "input: turn on emergency mode",
        "output: activate emergency mode",
        "input: enable emergency mode",
        "output: activate emergency mode",
        "input: activate emergency alert",
        "output: activate emergency mode",
        "input: start emergency mode",
        "output: activate emergency mode",
        "input: switch on emergency mode",
        "output: activate emergency mode",
        "input: emergency mode on",
        "output: activate emergency mode",
        "input: engage emergency mode",
        "output: activate emergency mode",
        "input: trigger emergency mode",
        "output: activate emergency mode",
        "input: activate safety mode",
        "output: activate emergency mode",
        "input: emergency mode activate",
        "output: activate emergency mode",
        "input: turn on alert mode",
        "output: activate emergency mode",
        "input: start emergency alert",
        "output: activate emergency mode",
        "input: enable safety mode",
        "output: activate emergency mode",
        "input: activate critical mode",
        "output: activate emergency mode",
        "input: engage emergency alert",
        "output: activate emergency mode",
        "input: turn on crisis mode",
        "output: activate emergency mode",
        "input: enable emergency protocol",
        "output: activate emergency mode",
        "input: switch to emergency mode",
        "output: activate emergency mode",
        "input: turn on emergency response",
        "output: activate emergency mode",
        f"input:{userinput} ",
        "output: ",
        ])

        print(response.text)


        # print("The VoiceAssist code is working properly.")

    elif (statement.startswith("navigateassist") or
          statement.startswith("navigate assist") or
          statement.startswith("navigate-assist") or
          statement.startswith("navigate asisst") or
          statement.startswith("navigateasist") or
          statement.startswith("navigateassit") or
          statement.startswith("navigate-a-sist") or
          statement.startswith("naves assist") or
          statement.startswith("navigate assistt") or
          statement.startswith("navigateist") or
          statement.startswith("navigateitassist") or
          statement.startswith("navigate assistence") or
          statement.startswith("navigate assistant") or 
          statement.startswith("naas assist") or
          statement.startswith("naav assist") or
          statement.startswith("navi assist") or
          statement.startswith("nava assist") or
          statement.startswith("navigate assistnts") or
          statement.startswith("navigate asst") or
          statement.startswith("nass assist") or
          statement.startswith("navigateasst") or
          statement.startswith("navigateassistance") or
          statement.startswith("navigate assists") or
          statement.startswith("navigateis assist") or
          statement.startswith("navigassist") or
          statement.startswith("navigate-assistt") or
          statement.startswith("navigateassistance") or
          statement.startswith("navigate-asists") or
          statement.startswith("navigassistt") or
          statement.startswith("navigateassistant") or
          statement.startswith("navigate-assistant") or
          statement.startswith("navi-assistant") or
          statement.startswith("navigate-a-assistant") or
          statement.startswith("navigateassistn") or
          statement.startswith("navigate assistzzz") or
          statement.startswith("navig-assistant") or
          statement.startswith("navigate-assistantt") or
          statement.startswith("navigateassistence") or
          statement.startswith("navigateassistt") or
          statement.startswith("navigate-assistn") or
          statement.startswith("navigate assistnts") or
          statement.startswith("navigat-assist") or
          statement.startswith("navigate-asist") or
          statement.startswith("navigate assistnts") or
          statement.startswith("navigate-a-sistant") or
          statement.startswith("nava-assist") or
          statement.startswith("naviassist") or
          statement.startswith("navigate-aassist") or
          statement.startswith("navigate-a-sistt")):
        


        response = model.generate_content([
        "input: turn left",
        "output: turn left",
        "input: take a left",
        "output: turn left",
        "input: make a left turn",
        "output: turn left",
        "input: left turn",
        "output: turn left",
        "input: turn to the left",
        "output: turn left",
        "input: go left",
        "output: turn left",
        "input: turn left now",
        "output: turn left",
        "input: make left",
        "output: turn left",
        "input: left please",
        "output: turn left",
        "input: take left",
        "output: turn left",
        "input: go left here",
        "output: turn left",
        "input: turn towards left",
        "output: turn left",
        "input: turn left at the next street",
        "output: turn left",
        "input: make a left at the intersection",
        "output: turn left",
        "input: left ahead",
        "output: turn left",
        "input: left turn now",
        "output: turn left",
        "input: take a left turn",
        "output: turn left",
        "input: head left",
        "output: turn left",
        "input: turn left at the next corner",
        "output: turn left",
        "input: turn left please",
        "output: turn left",
        "input: turn right",
        "output: turn right",
        "input: take a right",
        "output: turn right",
        "input: make a right turn",
        "output: turn right",
        "input: right turn",
        "output: turn right",
        "input: turn to the right",
        "output: turn right",
        "input: go right",
        "output: turn right",
        "input: turn right now",
        "output: turn right",
        "input: make right",
        "output: turn right",
        "input: right please",
        "output: turn right",
        "input: take right",
        "output: turn right",
        "input: go right here",
        "output: turn right",
        "input: turn towards right",
        "output: turn right",
        "input: turn right at the next street",
        "output: turn right",
        "input: make a right at the intersection",
        "output: turn right",
        "input: right ahead",
        "output: turn right",
        "input: right turn now",
        "output: turn right",
        "input: take a right turn",
        "output: turn right",
        "input: head right",
        "output: turn right",
        "input: turn right at the next corner",
        "output: turn right",
        "input: turn right please",
        "output: turn right",
        "input: move forward",
        "output: move forward",
        "input: go forward",
        "output: move forward",
        "input: drive forward",
        "output: move forward",
        "input: move ahead",
        "output: move forward",
        "input: go ahead",
        "output: move forward",
        "input: move straight ahead",
        "output: move forward",
        "input: drive straight",
        "output: move forward",
        "input: keep moving forward",
        "output: move forward",
        "input: head forward",
        "output: move forward",
        "input: go straight",
        "output: move forward",
        "input: move on",
        "output: move forward",
        "input: continue forward",
        "output: move forward",
        "input: advance forward",
        "output: move forward",
        "input: move straight ahead",
        "output: move forward",
        "input: proceed forward",
        "output: move forward",
        "input: move ahead now",
        "output: move forward",
        "input: keep going forward",
        "output: move forward",
        "input: go forward please",
        "output: move forward",
        "input: drive ahead",
        "output: move forward",
        "input: advance straight ahead",
        "output: move forward",
        "input: stop",
        "output: stop",
        "input: halt",
        "output: stop",
        "input: stop the car",
        "output: stop",
        "input: bring the car to a stop",
        "output: stop",
        "input: stop the vehicle",
        "output: stop",
        "input: stop now",
        "output: stop",
        "input: hold on",
        "output: stop",
        "input: stop moving",
        "output: stop",
        "input: brake",
        "output: stop",
        "input: stop here",
        "output: stop",
        "input: stop the engine",
        "output: stop",
        "input: stop the car please",
        "output: stop",
        "input: stop right here",
        "output: stop",
        "input: halt the car",
        "output: stop",
        "input: stop at this point",
        "output: stop",
        "input: bring it to a stop",
        "output: stop",
        "input: apply brakes",
        "output: stop",
        "input: car stop",
        "output: stop",
        "input: stop immediately",
        "output: stop",
        "input: pause",
        "output: stop",
        "input: reverse",
        "output: reverse",
        "input: back up",
        "output: reverse",
        "input: go in reverse",
        "output: reverse",
        "input: move backward",
        "output: reverse",
        "input: reverse the car",
        "output: reverse",
        "input: back the car up",
        "output: reverse",
        "input: move back",
        "output: reverse",
        "input: reverse now",
        "output: reverse",
        "input: go backward",
        "output: reverse",
        "input: back up the car",
        "output: reverse",
        "input: shift to reverse",
        "output: reverse",
        "input: back up now",
        "output: reverse",
        "input: car in reverse",
        "output: reverse",
        "input: reverse the vehicle",
        "output: reverse",
        "input: move in reverse",
        "output: reverse",
        "input: drive backwards",
        "output: reverse",
        "input: go in reverse gear",
        "output: reverse",
        "input: reverse please",
        "output: reverse",
        "input: shift back",
        "output: reverse",
        "input: go back",
        "output: reverse",
        "input: navigate to [destination]",
        "output: navigate to [destination]",
        "input: go to [destination]",
        "output: navigate to [destination]",
        "input: take me to [destination]",
        "output: navigate to [destination]",
        "input: drive to [destination]",
        "output: navigate to [destination]",
        "input: set navigation to [destination]",
        "output: navigate to [destination]",
        "input: start navigation to [destination]",
        "output: navigate to [destination]",
        "input: head to [destination]",
        "output: navigate to [destination]",
        "input: go towards [destination]",
        "output: navigate to [destination]",
        "input: direct me to [destination]",
        "output: navigate to [destination]",
        "input: show me the way to [destination]",
        "output: navigate to [destination]",
        "input: take me towards [destination]",
        "output: navigate to [destination]",
        "input: find the route to [destination]",
        "output: navigate to [destination]",
        "input: set the route to [destination]",
        "output: navigate to [destination]",
        "input: navigate towards [destination]",
        "output: navigate to [destination]",
        "input: start driving to [destination]",
        "output: navigate to [destination]",
        "input: set destination to [destination]",
        "output: navigate to [destination]",
        "input: take the route to [destination]",
        "output: navigate to [destination]",
        "input: start journey to [destination]",
        "output: navigate to [destination]",
        "input: go to [destination] now",
        "output: navigate to [destination]",
        "input: direct me towards [destination]",
        "output: navigate to [destination]",
        f"input:{userinput} ",
        "output: ",
        ])
        print(response.text)
        # print("The NavAssist is working properly.")
    
    else: 
        print("No proper command.")












